---
title: "Stewardship testimonial"
description: "Notes from my stewardship testimonial at church"
author: "Ben Jaques-Leslie"
date: "2023-11-07"
categories:
  - church
---

On Sunday, I shard some thoughts about why giving to [my church](https://www.spucconsummit.org/) is important to the work on the Ministry of Social Justice and Outreach on which I'm a new member. Here are my notes:

> Hello everyone. I'm Ben Jaques-Leslie. I'm a member of the Ministry of Social Justice and Outreach. I'd like to share some about how your giving to the church supports the work of this ministry and why I think that's important. \
> \
> For me, activism and working toward social justice came before church. The home I grew up in was full of academic books about religion, but anti-church-going. In high school, I started to be interested in social issues. I joined clubs, attended rallies, protested. And while it sometimes takes time to explain, my career choices have been motivated by the desire to pursue equity and increase freedom. \
> \
> What is most exciting to me about our work in the Ministry of Social Justice and Outreach is the understanding that social justice is not a single issue, but part of all that we do. Marginalization and oppression are not simple problems to be solved, because they are integrated into our society and psychology. That sounds pretty overwhelming, but I like to think of it this way. If oppressions is so knitted into our world, then we have many opportunities to struggle against it. In our language, in how we spend money, in how we vote, we have so many ways to pursue justice. \
> \
> And in the Ministry of Social Justice and Outreach, we are trying to connect through out the church to pursue justice in many different ways, leveraging capacities and interests of other ministries and members. Next year we plan to spend 13% of pledged giving on supporting community partners. These partners include Interfaith Action (which is also the Dept. of Indian Work, Project Home, and Opportunity Partners like a free legal clinic). Also partners including Habitat for Humanity, reparations work through Indian Land Tenure, Minnesota Interfaith power and light for environmental justice, and the wider work of Our Church\'s Wider Mission, which supports the UCC and their work on LGBTQ issues, Racial Justice, and Disaster Assistance. \
> \
> The work of our Ministry is broad, internal and outreaching, much like the challenges we see improving equity and fighting for social justice. Thank you for your giving.
